name: 'Mike Ball'
description: 'Check that a given GitHub release tag does not already exist'
author: 'mdb'
inputs:
  tag:
    required: true
    description: 'The release tag to check for'
  token:
    required: true
    description: 'A GitHub access token'
  failure-message:
    required: false
    description: 'An optional customized message to display on failure'
  skip-commit-message-pattern:
    required: false
    description: 'If the specified skip-commit-message-pattern is present in the specified commit-message, skip unpublished release tag evaluation and succeed'
  commit-message:
    required: false
    description: 'The commit message. Required if skip-commit-message-pattern is specified.'
  skip-authors:
    required: false
    description: 'If any of the specified newline-separated list of skip-authors matches the specified author, skip unpublished release tag evaluation and succeed'
  author:
    required: false
    description: 'The commit author. Required if skip-author is specified.'

runs:
  using: 'node20'
  main: 'dist/index.js'
