name: 'Mike Ball'
description: 'Check that a given GitHub release tag does not already exist'
author: 'mdb'
inputs:
  tag:
    required: true
    description: 'The release tag to check for'
runs:
  using: 'node12'
  main: 'dist/index.js'
