name: 'Mike Ball'
description: 'Check that a given GitHub release tag does not already exist'
author: 'mdb'
inputs:
  tag:
    required: true
    description: 'The release tag to check for'
  token:
    required: true
    description: 'A GitHub access token'
  fail:
    type: boolean
    required: false
    description: 'Whether or not to fail the action if the release tag has already been published'
    default: true
runs:
  using: 'node16'
  main: 'dist/index.js'
